import { ExternalLink, KeyRound } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Suspense } from "react";
import { BriefSkeleton, BriefView } from "@/components/research-brief";
import { VenueBadge } from "@/components/venue-badge";
import { hasAnthropicKey } from "@/lib/anthropic";
import { fetchKalshiMarketByTicker } from "@/lib/kalshi";
import { fetchPolymarketMarketBySlug } from "@/lib/polymarket";
import { generateResearchBrief } from "@/lib/research";
import type { UnifiedMarket } from "@/lib/types";
import { formatPrice, formatUsd, relativeDate } from "@/lib/utils";

export const revalidate = 30;
export const dynamic = "force-dynamic";

interface PageParams {
  venue: string;
  slug: string;
}

async function fetchMarket(
  venue: string,
  slug: string,
): Promise<UnifiedMarket | null> {
  const decoded = decodeURIComponent(slug);
  if (venue === "polymarket") return fetchPolymarketMarketBySlug(decoded);
  if (venue === "kalshi") return fetchKalshiMarketByTicker(decoded);
  return null;
}

export default async function ResearchPage({
  params,
}: {
  params: Promise<PageParams>;
}) {
  const { venue, slug } = await params;
  const market = await fetchMarket(venue, slug);
  if (!market) notFound();

  return (
    <div className="mx-auto max-w-3xl space-y-8">
      <Link
        href="/markets"
        className="text-sm text-[var(--color-muted)] hover:text-[var(--color-text)]"
      >
        ← Back to markets
      </Link>

      <MarketHeader market={market} />

      <div className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6 shadow-[var(--shadow-card)] sm:p-8">
        {hasAnthropicKey() ? (
          <Suspense fallback={<BriefSkeleton />}>
            <BriefStream market={market} />
          </Suspense>
        ) : (
          <SetupPrompt />
        )}
      </div>
    </div>
  );
}

async function BriefStream({ market }: { market: UnifiedMarket }) {
  try {
    const brief = await generateResearchBrief(market);
    return <BriefView brief={brief} marketYesPrice={market.yesPrice} />;
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    return (
      <div className="rounded-md border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">
        <div className="font-medium">Could not generate brief</div>
        <div className="mt-1 font-mono text-xs">{message}</div>
      </div>
    );
  }
}

function MarketHeader({ market }: { market: UnifiedMarket }) {
  return (
    <div className="space-y-4">
      <VenueBadge venue={market.venue} />
      <h1 className="text-3xl font-semibold leading-tight tracking-tight">
        {market.title}
      </h1>
      <div className="flex flex-wrap items-center gap-x-6 gap-y-2 text-sm text-[var(--color-muted)]">
        <span>
          YES{" "}
          <span className="font-mono text-[var(--color-positive)]">
            {formatPrice(market.yesPrice)}
          </span>
        </span>
        <span>
          NO{" "}
          <span className="font-mono text-[var(--color-negative)]">
            {formatPrice(market.noPrice)}
          </span>
        </span>
        {market.volume24h ? (
          <span>24h vol {formatUsd(market.volume24h)}</span>
        ) : null}
        {market.endDate ? <span>Resolves {relativeDate(market.endDate)}</span> : null}
        <a
          href={market.url}
          target="_blank"
          rel="noreferrer"
          className="inline-flex items-center gap-1 text-[var(--color-accent-strong)] hover:underline"
        >
          Open on {market.venue} <ExternalLink className="h-3 w-3" />
        </a>
      </div>
    </div>
  );
}

function SetupPrompt() {
  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 text-xs uppercase tracking-wider text-[var(--color-muted)]">
        <KeyRound className="h-3.5 w-3.5 text-[var(--color-accent)]" />
        AI research brief — setup required
      </div>
      <h2 className="text-2xl font-semibold tracking-tight">
        Add an Anthropic API key to enable briefs
      </h2>
      <p className="text-sm leading-relaxed text-[var(--color-muted)]">
        Research briefs are generated by Claude Sonnet 4.6 with prompt
        caching. To enable them, set <code className="font-mono">ANTHROPIC_API_KEY</code> in
        your environment and redeploy.
      </p>
      <pre className="overflow-x-auto rounded-md border border-[var(--color-border)] bg-[var(--color-surface-2)] p-3 text-xs">
        <code>echo &apos;ANTHROPIC_API_KEY=sk-ant-…&apos; &gt;&gt; .env.local</code>
      </pre>
      <p className="text-xs text-[var(--color-muted)]">
        Get a key from{" "}
        <a
          href="https://console.anthropic.com/"
          target="_blank"
          rel="noreferrer"
          className="text-[var(--color-accent-strong)] underline"
        >
          console.anthropic.com
        </a>
        .
      </p>
    </div>
  );
}
