import { RESEARCH_MODEL, getAnthropicClient } from "./anthropic";
import type { UnifiedMarket } from "./types";

export { MissingAnthropicKeyError } from "./anthropic";

/**
 * Structured research brief for a single prediction market.
 *
 * Generated by Claude via tool-use so the output is guaranteed-shape JSON
 * with no parsing fragility. The system prompt is marked with
 * `cache_control: ephemeral` so repeated calls within ~5 minutes pay only
 * the cache-read rate on the prompt tokens — a meaningful saving once
 * users start clicking briefs in succession.
 */
export interface ResearchBrief {
  restatedQuestion: string;
  background: string;
  baseRates: string;
  catalysts: string[];
  counterarguments: string[];
  bottomLine: string;
  /** Model's estimate of fair value, 0..1 probability of YES. */
  fairValueEstimate?: number;
  /** Self-rated confidence in the brief. */
  confidence?: "low" | "medium" | "high";
}

const SYSTEM_PROMPT = `You are a quantitative research analyst writing decision-support briefs for sophisticated prediction-market traders.

For each market, produce a brief with these sections:

1. RESTATED QUESTION — restate the market in plain language so resolution criteria are unambiguous.
2. BACKGROUND — 2–3 sentences of context for someone unfamiliar with the topic.
3. BASE RATES — historical frequencies relevant to this question. Cite the reference class explicitly (e.g. "incumbent presidents seeking re-election won 60% of contests since 1900").
4. KEY CATALYSTS — 3–5 specific, observable upcoming events that would move the market.
5. COUNTERARGUMENTS — 2–3 reasons the current consensus could be wrong.
6. BOTTOM LINE — one sentence: where do you think fair value sits relative to the market price, and how confident are you?

Constraints:
- Be specific and concrete. Skip filler, hedging language, and disclaimers.
- If you don't know a fact, say so explicitly. Never fabricate statistics, polls, or quotes.
- Your audience is sophisticated. Don't explain what a prediction market is.
- Express probabilities as fractions of 1 (e.g. 0.62, not "62%") in the structured output.
- Always call the submit_brief tool — never reply in plain text.`;

const BRIEF_TOOL = {
  name: "submit_brief",
  description: "Submit the final structured research brief for the user.",
  input_schema: {
    type: "object" as const,
    properties: {
      restatedQuestion: {
        type: "string",
        description: "The market question, restated for clarity.",
      },
      background: {
        type: "string",
        description: "2–3 sentences of context.",
      },
      baseRates: {
        type: "string",
        description:
          "Historical base rates for the relevant reference class, with the reference class named.",
      },
      catalysts: {
        type: "array",
        items: { type: "string" },
        description: "3–5 specific upcoming events that would move the market.",
        minItems: 3,
        maxItems: 5,
      },
      counterarguments: {
        type: "array",
        items: { type: "string" },
        description: "2–3 reasons the consensus might be wrong.",
        minItems: 2,
        maxItems: 3,
      },
      bottomLine: {
        type: "string",
        description:
          "One sentence: fair value vs market price, and confidence.",
      },
      fairValueEstimate: {
        type: "number",
        description:
          "Your estimated probability of YES, as a fraction in [0, 1].",
        minimum: 0,
        maximum: 1,
      },
      confidence: {
        type: "string",
        enum: ["low", "medium", "high"],
        description: "Self-rated confidence in the brief.",
      },
    },
    required: [
      "restatedQuestion",
      "background",
      "baseRates",
      "catalysts",
      "counterarguments",
      "bottomLine",
    ],
  },
};

function buildUserPrompt(market: UnifiedMarket): string {
  const lines = [
    `Market: ${market.title}`,
    `Venue: ${market.venue}`,
    `Current YES price: ${(market.yesPrice * 100).toFixed(1)}¢ (= ${market.yesPrice.toFixed(3)} probability)`,
  ];
  if (market.endDate) lines.push(`Resolves: ${market.endDate}`);
  if (market.category) lines.push(`Category: ${market.category}`);
  if (market.volume24h)
    lines.push(`24h volume: $${market.volume24h.toLocaleString()}`);
  if (market.description) {
    lines.push("");
    lines.push("Resolution criteria / description:");
    lines.push(market.description);
  }
  lines.push("");
  lines.push("Generate the brief now via the submit_brief tool.");
  return lines.join("\n");
}

/**
 * Generate a research brief for a market using Claude with prompt caching.
 *
 * Throws MissingAnthropicKeyError if no API key is configured — callers
 * should catch this and render a setup prompt instead of a generic error.
 */
export async function generateResearchBrief(
  market: UnifiedMarket,
): Promise<ResearchBrief> {
  const client = getAnthropicClient();

  const response = await client.messages.create({
    model: RESEARCH_MODEL,
    max_tokens: 1500,
    system: [
      {
        type: "text",
        text: SYSTEM_PROMPT,
        cache_control: { type: "ephemeral" },
      },
    ],
    tools: [BRIEF_TOOL],
    tool_choice: { type: "tool", name: "submit_brief" },
    messages: [
      {
        role: "user",
        content: buildUserPrompt(market),
      },
    ],
  });

  const toolBlock = response.content.find(
    (b): b is Extract<typeof b, { type: "tool_use" }> => b.type === "tool_use",
  );
  if (!toolBlock || toolBlock.name !== "submit_brief") {
    throw new Error(
      "Claude did not return a structured brief. Stop reason: " +
        response.stop_reason,
    );
  }
  return toolBlock.input as ResearchBrief;
}
